---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Module-C-IAM Roles"
# yamllint disable rule:line-length
######################################################################
# Parameters
######################################################################
Parameters:

  AppName:
    Type: String

  Environment:
    Type: String
    AllowedValues:
      - 'dev'
      - 'qa'
      - 'prod'
######################################################################
# Resource creation
######################################################################
Resources:
  ######################################################################
  # Instance role
  ######################################################################
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/CloudWatchAgentAdminPolicy
        - arn:aws:iam::aws:policy/AmazonRDSFullAccess
      Policies:
        - PolicyName: s3access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '{{resolve:ssm:/s3/private/arn}}'
        - PolicyName: efsaccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: '*'
                Resource:
                  - !Sub "arn:aws:elasticfilesystem:${AWS::Region}:${AWS::AccountId}:file-system/'{{resolve:ssm:/efs/filesystem/id}}'"
        - PolicyName: getsecret
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'
#                   - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:MySecretForDBtestdb*"
  InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref InstanceRole
  ######################################################################
  # Parameter store parameters
  ######################################################################
  InstanceProfileNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ["/", ["/iam", "instanceprofile", "name"]]
      Type: "String"
      Description: Name of Instance Profile
      Value: !Ref InstanceProfile

  InstanceProfileArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ["/", ["/iam", "instanceprofile", "arn"]]
      Type: "String"
      Description: ARN of Instance Profile
      Value: !GetAtt InstanceProfile.Arn

  InstanceRoleNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ["/", ["/iam", "instancerole", "name"]]
      Type: "String"
      Description: Name of Instance Role
      Value: !Ref InstanceRole
