---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Module-C-S3Bucket"
# yamllint disable rule:line-length
######################################################################
# Parameters
######################################################################
Parameters:

  AppName:
    Type: String

  Encryption:
    Type: String
    AllowedValues:
      - 'enabled'
      - 'disabled'

  PublicAccess:
    Type: String
    AllowedValues:
      - 'enabled'
      - 'disabled'

  Versioning:
    Type: String
    AllowedValues:
      - 'enabled'
      - 'disabled'
  Environment:
    Type: String
    AllowedValues:
      - 'dev'
      - 'qa'
      - 'prod'

Conditions:
  IsEncrypted:
    !Equals [!Ref Encryption, 'enabled']
  IsPublic:
    !Equals [!Ref PublicAccess, 'enabled']
  IsVersioning:
    !Equals [!Ref Versioning, 'enabled']
######################################################################
# Resource creation
######################################################################
Resources:
  ######################################################################
  # S3 BUCKET
  ######################################################################
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join ["-", [!Ref AppName, !Ref AWS::AccountId, !If [IsPublic, "public", "private"], !Ref Environment]]
      BucketEncryption: !If
        - IsEncrypted
        - ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
        - AWS::NoValue
      PublicAccessBlockConfiguration: !If
        - IsPublic
        - BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
        - BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
      VersioningConfiguration: !If
        - IsVersioning
        - Status: Enabled
        - AWS::NoValue
      Tags:
        - Key: name
          Value: !Ref AppName
  ######################################################################
  # Parameter store parameters
  ######################################################################
  S3BucketName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ["/", ["/s3", !Ref S3Bucket, "name"]]
      Type: "String"
      Description: Name of bucket
      Value: !Ref S3Bucket

  S3ARN:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ["/", ["/s3", !Ref S3Bucket, "arn"]]
      Type: "String"
      Description: ARN of bucket
      Value: !GetAtt S3Bucket.Arn
######################################################################
# Outputs
######################################################################
Outputs:
  S3BucketPublicDNSName:
    Description: The DNS Name of the S3 Public Bucket
    Value: !GetAtt S3Bucket.RegionalDomainName

  S3BucketName:
    Description: The Name of the S3 Public
    Value: !Ref S3Bucket 
