---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Module-A-VPC"
# yamllint disable rule:line-length
######################################################################
# Parameters
######################################################################
Parameters:

  VpcName:  # Parameters name of VPC
    Type: String
    Default: "VPC"

  VpcCidr:  # CIDR Range for VPC subnet range
    Type: String
    Default: "10.0.0.0/25"
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/([0-9]|[1-2][0-9]|3[0-2]))$"

  PublicSubnetACidr:  # CIDR Range in first zone (named as PublicSubnetACidr)
    Type: String
    Default: "10.0.0.32/28"
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/([0-9]|[1-2][0-9]|3[0-2]))$"

  PublicSubnetBCidr:  # CIDR Range in second zone (named as PublicSubnetBCidr)
    Type: String
    Default: "10.0.0.48/28"
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/([0-9]|[1-2][0-9]|3[0-2]))$"

  PrivateSubnetApplicationACidr:  # CIDR Range in first zone for application
    Type: String
    Default: "10.0.0.0/28"
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/([0-9]|[1-2][0-9]|3[0-2]))$"

  PrivateSubnetApplicationBCidr:  # CIDR Range in second zone for applicaiton
    Type: String
    Default: "10.0.0.16/28"
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/([0-9]|[1-2][0-9]|3[0-2]))$"

  PrivateSubnetDatabaseACidr:   # CIDR Range in first zone for database
    Type: String
    Default: "10.0.0.64/28"
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/([0-9]|[1-2][0-9]|3[0-2]))$"

  PrivateSubnetDatabaseBCidr:   # CIDR Range in second zone for database
    Type: String
    Default: "10.0.0.80/28"
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/([0-9]|[1-2][0-9]|3[0-2]))$"

######################################################################
# Resource creation
######################################################################
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref VpcName
  ######################################################################
  # Public Subnets
  ######################################################################
  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref PublicSubnetACidr
      VpcId: !Ref VPC
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select
        - '0'
        - !GetAZs ''
      Tags:
        - Key: Name
          Value: PublicSubnetA

  PublicSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref PublicSubnetBCidr
      VpcId: !Ref VPC
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select
        - '1'
        - !GetAZs ''
      Tags:
        - Key: Name
          Value: PublicSubnetB
  ######################################################################
  # Private Subnets for Application and Databases
  ######################################################################
  PrivateSubnetApplicationA:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref PrivateSubnetApplicationACidr
      VpcId: !Ref VPC
      MapPublicIpOnLaunch: false
      AvailabilityZone: !Select
        - '0'
        - !GetAZs ''
      Tags:
        - Key: Name
          Value: PrivateSubnetApplicationA

  PrivateSubnetApplicationB:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref PrivateSubnetApplicationBCidr
      VpcId: !Ref VPC
      MapPublicIpOnLaunch: false
      AvailabilityZone: !Select
        - '1'
        - !GetAZs ''
      Tags:
        - Key: Name
          Value: PrivateSubnetApplicationB

  PrivateSubnetDatabaseA:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref PrivateSubnetDatabaseACidr
      VpcId: !Ref VPC
      MapPublicIpOnLaunch: false
      AvailabilityZone: !Select
        - '0'
        - !GetAZs ''
      Tags:
        - Key: Name
          Value: PrivateSubnetDatabaseA

  PrivateSubnetDatabaseB:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref PrivateSubnetDatabaseBCidr
      VpcId: !Ref VPC
      MapPublicIpOnLaunch: false
      AvailabilityZone: !Select
        - '1'
        - !GetAZs ''
      Tags:
        - Key: Name
          Value: PrivateSubnetDatabaseB
  ######################################################################
  # Internet Gateway
  ######################################################################
  InternetGateway:
    Type: AWS::EC2::InternetGateway


  InternetGatewayToVPC:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
  ######################################################################
  # Elastic IP's
  ######################################################################
  NatGatewayPublicIpAddressA:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  NatGatewayPublicIpAddressB:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  ######################################################################
  # Nat Gateway's
  ######################################################################
  NatGatewayA:
    Type: AWS::EC2::NatGateway
    Properties:
      SubnetId: !Ref PublicSubnetA
      AllocationId: !GetAtt NatGatewayPublicIpAddressA.AllocationId

  NatGatewayB:
    Type: AWS::EC2::NatGateway
    Properties:
      SubnetId: !Ref PublicSubnetB
      AllocationId: !GetAtt NatGatewayPublicIpAddressB.AllocationId
  ######################################################################
  # Route Tables
  ######################################################################
  PublicRouteTableA:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: PublicRouteTableA

  PublicRouteTableB:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: PublicRouteTableB

  PrivateRouteTableApplicationA:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: AppRouteTableA

  PrivateRouteTableApplicationB:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: AppRouteTableB

  PrivateRouteTableDatabaseA:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: DBRouteTableA

  PrivateRouteTableDatabaseB:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: DBRouteTableB
  ######################################################################
  # Route Tables to Subnet Association
  ######################################################################
  PublicRouteTableToPublicSubnetA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTableA
      SubnetId: !Ref PublicSubnetA

  PublicRouteTableToPublicSubnetB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTableB
      SubnetId: !Ref PublicSubnetB

  PrivateRouteTableApplicationAToPrivateSubnetApplicationA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTableApplicationA
      SubnetId: !Ref PrivateSubnetApplicationA

  PrivateRouteTableApplicationBToPrivateSubnetApplicationB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTableApplicationB
      SubnetId: !Ref PrivateSubnetApplicationB

  PrivateRouteTableDatabaseAToPrivateSubnetDatabaseA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTableDatabaseA
      SubnetId: !Ref PrivateSubnetDatabaseA

  PrivateRouteTableDatabaseBToPrivateSubnetDatabaseB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTableDatabaseB
      SubnetId: !Ref PrivateSubnetDatabaseB
  ######################################################################
  # Routes
  ######################################################################
  RouteToInternetPublicA:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTableA
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  RouteToInternetPublicB:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTableB
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  RouteToInternetApplicationA:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTableApplicationA
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGatewayA

  RouteToInternetApplicationB:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTableApplicationB
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGatewayB

  RouteToInternetDatabaseA:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTableDatabaseA
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGatewayA

  RouteToInternetDatabaseB:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTableDatabaseB
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGatewayB
  ######################################################################
  # Parameter store parameters
  ######################################################################
  VPCId:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: "/vpc/id"
      Type: "String"
      Description: VPC Id
      Value: !Ref VPC

  PublicSubnetAId:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/vpc/subnet/public/a/id"
      Type: "String"
      Description: PublicSubnetA Id
      Value: !Ref PublicSubnetA

  PublicSubnetBId:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/vpc/subnet/public/b/id"
      Type: "String"
      Description: PublicSubnetB Id
      Value: !Ref PublicSubnetB

  PrivateSubnetApplicationAId:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/vpc/subnet/private/application/a/id"
      Type: "String"
      Description: PrivateSubnetApplicationA Id
      Value: !Ref PrivateSubnetApplicationA

  PrivateSubnetApplicationBId:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/vpc/subnet/private/application/b/id"
      Type: "String"
      Description: PrivateSubnetApplicationB Id
      Value: !Ref PrivateSubnetApplicationB

  PrivateSubnetApplicationACidrParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/vpc/subnet/private/application/a/cidr"
      Type: "String"
      Description: PrivateSubnetApplicationA cidr
      Value: !Ref PrivateSubnetApplicationACidr

  PrivateSubnetApplicationBCidrParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/vpc/subnet/private/application/b/cidr"
      Type: "String"
      Description: PrivateSubnetApplicationB cidr
      Value: !Ref PrivateSubnetApplicationBCidr

  PrivateSubnetDatabaseAId:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/vpc/subnet/private/database/a/id"
      Type: "String"
      Description: PrivateSubnetDatabaseA Id
      Value: !Ref PrivateSubnetDatabaseA

  PrivateSubnetDatabaseBId:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/vpc/subnet/private/database/b/id"
      Type: "String"
      Description: PrivateSubnetDatabaseB Id
      Value: !Ref PrivateSubnetDatabaseB
