---
name: AWS CloudFormation "Deploy CloudFormation Stack" Action for GitHub Actions

on: 
  push:
    branches: [ main ]

jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code from master branch
        uses: actions/checkout@v2

      # Configure AWS Credential
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.ACCESS_KEY_SECRET }}
          aws-region: eu-central-1

      # Deploy to AWS CloudFormation
      - name: Deploy to AWS CloudFormation VPC
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: assessment-vpc-stack
          template: templates/vpc.yaml
          no-fail-on-empty-changeset: "1"

      - name: Deploy to AWS CloudFormation S3 bucket
        id: s3
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: assessment-s3-private-stack
          template: templates/s3bucket.yaml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: >-
            AppName=testapp,
            Encryption=enabled,
            PublicAccess=disabled,
            Versioning=enabled,
            Environment=dev

      - name: Deploy to AWS CloudFormation EFS template
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: assessment-efs-stack
          template: templates/efs.yaml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: >- 
            Application=testapp,
            Environment=dev,
            Encrypted=true

      - name: Deploy to AWS CloudFormation RDS template
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: assessment-rds-stack
          template: templates/rds.yaml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: >- 
            Environment=dev,
            InstanceId=testinstance,
            DatabaseName=testdb, 
            DatabaseUser=testuser,
            InstanceType=db.t3.micro,
            StorageSize=20,
            EngineType=mysql,
            EngineVersion=8.0.16

      - name: Deploy to AWS CloudFormation InstanceRole
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: assessment-instancerole-stack
          template: templates/instancerole.yaml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: >- 
            AppName=testapp,
            Environment=dev
                  
      - name: Deploy to AWS CloudFormation Instance template
        id: instance-stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: assessment-instance-stack
          template: templates/instance.yaml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: >- 
            AppName=testapp,
            Environment=dev,
            InstanceType=t2.micro,
            MinInstances=2,
            MaxInstances=4,
            DesiredInstances=2,
            AMI=/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2,
            SSLCertificateARN=arn:aws:acm:eu-central-1:735556469799:certificate/efcf013c-a3a1-4213-8991-c8e78ec35107,
            CPUPolicyTargetValue=80,
            WordpressUser=WordpressAdmin,
            WordpressEmail=admin@wordpress.com,
            WPDomainName=team4.nordcloudtap.com

#       - name: Output for ALB DNS Name
#         id: DNS 
#         run: |
#           echo "::set-output name=ALB::$PublicAlbDnsName"
#           echo "::set-output name=S3DNS::$PublicS3DnsName"
#           echo "::set-output name=S3Name::$PublicS3Name"
#         env:
#           PublicAlbDnsName: ${{ steps.instance-stack.outputs.LoadBalancerDNSName }}
#           PublicS3DnsName: ${{ steps.s3.outputs.S3BucketPublicDNSName }}
#           PublicS3Name: ${{ steps.s3.outputs.S3BucketName }}
